app/models/user.py
from app import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(200), nullable=False)
    fullname = db.Column(db.String(100), nullable=False)
    qualification = db.Column(db.String)
    dob = db.Column(db.Date)
    is_admin = db.Column(db.Boolean, default=False)

    scores = db.relationship('Score', backref='user', lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    @classmethod
    def get_all_users(cls):
        return cls.query.filter(cls.username != "admin@quiz.com").all()

app/controllers/users_controller.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from app import db
from flask_login import current_user, login_required
from random import shuffle
from app.forms import UserDetailsForm, ChangePasswordForm
from app.models.chapter import Chapter
from app.models.quiz import Quiz
from app.models.score import Score
from app.models.subject import Subject
from app.models.user import User

users_bp = Blueprint('users', __name__)

@users_bp.route("/dashboard")
@login_required
def dashboard():
    scores = Score.query.filter_by(user_id=current_user.id).all()
    total_attempted_quizzes = len(scores)

    average_score = sum([s.total_scored for s in scores]) / total_attempted_quizzes if total_attempted_quizzes > 0 else 0

    return render_template("user/dashboard.html",
                           scores=scores,
                           total_attempted_quizzes=total_attempted_quizzes,
                           average_score=average_score)

@users_bp.route("/attempt_quiz/<int:quiz_id>", methods=['GET', 'POST'])
@login_required
def attempt_quiz(quiz_id):
    quiz = Quiz.query.get_or_404(quiz_id)
    questions = quiz.questions.copy()
    shuffle(questions)
    if request.method == 'POST':
        score = 0
        for question in questions:
            user_answer = request.form.get(f'question_{question.id}')
            if user_answer and int(user_answer) == question.correct_option:
                score += 1
        user_score = Score(
            total_scored=score,
            quiz_id=quiz_id,
            user_id=current_user.id
        )
        db.session.add(user_score)
        db.session.commit()
        flash(f'Quiz completed! Your score: {score} / {len(questions)}', category="success")
        return redirect(url_for("users.quiz_results", quiz_id=quiz_id))
    return render_template("user/attempt_quiz.html", quiz=quiz, questions=questions)

@users_bp.route("/quiz_results/<int:quiz_id>")
@login_required
def quiz_results(quiz_id):
    quiz = Quiz.query.get_or_404(quiz_id)
    score = Score.query.filter_by(user_id=current_user.id, quiz_id=quiz_id).first()
    return render_template("user/quiz_results.html", quiz=quiz, score=score)

@users_bp.route("/leaderboard")
@login_required
def leaderboard():
    users = User.get_all_users()
    leaderboard_data = []

    for user in users:
        scores = Score.query.filter_by(user_id=user.id).all()
        total_score = sum([s.total_scored for s in scores])
        leaderboard_data.append({
            "user_fullname": user.fullname,
            "total_score": total_score
        })
    leaderboard_data.sort(key=lambda x: x['total_score'], reverse=True)
    user_fullnames = [x['user_fullname'] for x in leaderboard_data]
    user_total_scores = [x['total_score'] for x in leaderboard_data]
    return render_template("user/leaderboard.html",
                           leaderboard_data=leaderboard_data,
                           user_fullnames=user_fullnames,
                           user_total_scores=user_total_scores)

@users_bp.route("/select-quiz", methods=['GET', 'POST'])
@login_required
def select_quiz():
    subjects = Subject.query.all()
    chapters = Chapter.query.all()
    quizzes = Quiz.query.all()

    if request.method == 'POST':
        subject_id = request.form.get('subject_id')
        chapter_id = request.form.get('chapter_id')

        if subject_id:
            quizzes = Quiz.query.join(Chapter).filter(Chapter.subject_id == subject_id).all()
        if chapter_id:
            quizzes = Quiz.query.filter_by(chapter_id=chapter_id).all()

    return render_template("user/select-quiz.html",
                           subjects=subjects,
                           chapters=chapters,
                           quizzes=quizzes)

@users_bp.route("/update-profile", methods=['GET', 'POST'])
@login_required
def update_profile():
    user = current_user
    form = UserDetailsForm(obj=user)

    if form.validate_on_submit():
        user.username = form.username.data
        user.fullname = form.fullname.data
        user.qualification = form.qualification.data
        user.dob = form.dob.data

        db.session.commit()
        flash("User details updated successfully!", category="success")
        return redirect(url_for("users.dashboard"))

    return render_template("user/update-profile.html",
                           form=form,
                           user=user)

@users_bp.route("/change-password", methods=['GET', 'POST'])
@login_required
def change_password():
    user = current_user
    form = ChangePasswordForm(obj=user)

    if form.validate_on_submit():
        user.set_password(form.password.data)

        db.session.commit()
        flash("Password has been changed successfully!", category="success")
        return redirect(url_for("users.dashboard"))

    return render_template("user/change-password.html",
                           form=form,
                           user=user)

app/templates/user/attempt_quiz.html
{% extends "layout.html" %}
{% block title %}Attempt Quiz: {{quiz.name}}{% endblock %}
{% block content %}
<h1 class="page-title">{{quiz.name}}</h1>

{% if quiz.time_duration > 0 %}
<span id="timer" class="quiz-timer">00:00</span>
{% endif %}

<form id="quizForm" class="quiz-form" method="POST">
    {% for question in questions %}
    <div class="quiz-question">
        <div class="question-number">Question #{{ loop.index }}</div>
        <div class="question-statement">{{ question.question_statement }}</div>
        <div class="quiz-options">
            {% for option in [question.option1, question.option2, question.option3, question.option4] %}
            <label class="radio-option">
                <input type="radio" name="question_{{ question.id }}" value="{{ loop.index }}" required>
                {{ option }}
            </label>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary btn-block">Submit Quiz</button>
</form>


<script>
    const quizDuration = {{ quiz.time_duration }};
    if (quizDuration > 0) {
        let timeLeft = quizDuration;

        function updateTimer() {
            let minutes = Math.floor(timeLeft / 60)
            let seconds = timeLeft % 60
            document.getElementById("timer").textContent = `
    ${minutes.toString().padStart(2, '0')}:
    ${seconds.toString().padStart(2, '0')}
    `
            if (timeLeft <= 0) {
                clearInterval(timeInterval);
                alert("Time's up! Your quiz will be submitted automatically.");
                document.getElementById("quizForm").submit()
            } else {
                timeLeft--;
            }
        }

        const timeInterval = setInterval(updateTimer, 1000)
    }
</script>
{% endblock %}

app/templates/user/change-password.html
{% extends "layout.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
<h1 class="page-title">Change Password</h1>

<form method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.password.label(class_="form-label") }}
        {{ form.password(size=32, class_="form-control") }}
        {% if form.password.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.confirm_password.label(class_="form-label") }}
        {{ form.confirm_password(size=32, class_="form-control") }}
        {% if form.confirm_password.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.confirm_password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.submit(class_="btn btn-primary") }}
    </div>
</form>
{% endblock %}

app/templates/user/dashboard.html
{% extends "layout.html" %}
{% block title %}User Dashboard{% endblock %}
{% block content %}
<h1 class="page-title">User Dashboard</h1>

<section class="mb-6">
    <div class="row gap-6">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h3 class="mb-3">Your Details</h3>
                    <div class="detail-item">
                        <span class="detail-key">Username:</span>
                        <span class="detail-value">{{ current_user.username }}</span>
                    </div>

                    <div class="detail-item">
                        <span class="detail-key">Full Name:</span>
                        <span class="detail-value">{{ current_user.fullname }}</span>
                    </div>

                    <div class="detail-item">
                        <span class="detail-key">Qualification:</span>
                        <span class="detail-value">{{ current_user.qualification }}</span>
                    </div>

                    <div class="detail-item">
                        <span class="detail-key">DOB:</span>
                        <span class="detail-value">{{ current_user.dob }}</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h3 class="mb-3">Progress Summary</h3>
                    <div class="detail-item">
                        <span class="detail-key">Total Attempted Quizzes:</span>
                        <span class="detail-value">{{ total_attempted_quizzes }}</span>
                    </div>

                    <div class="detail-item">
                        <span class="detail-key">Average Score:</span>
                        <span class="detail-value">{{ average_score|round(2) }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mb-6">
    <div class="card">
        <div class="card-body">
            <h3 class="mb-3">Quiz History</h3>
            <div class="table-container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Quiz Name</th>
                            <th>Attempted Time</th>
                            <th>Total Scored</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for score in scores %}
                        <tr>
                            <td>{{ score.quiz.name }}</td>
                            <td>{{ score.timestamp.strftime("%Y-%m-%d %H:%M") }}</td>
                            <td>{{ score.total_scored }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</section>

{% endblock %}

app/templates/user/leaderboard.html
{% extends "layout.html" %}
{% block title %}Leaderboard{% endblock %}
{% block head %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}
{% block content %}
<h1 class="page-title">Leaderboard</h1>

<div class="card">
    <div class="card-body">
        <canvas id="leaderboardChart"></canvas>
    </div>
</div>

<script>
    const ctx = document.getElementById('leaderboardChart');

    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: {{ user_fullnames| tojson }},
        datasets: [{
            label: 'Total Score',
            data: {{ user_total_scores| tojson }},
        borderWidth: 1,
        backgroundColor: 'rgba(75, 192, 192, 0.2)',
        borderColor: 'rgba(75, 192, 192, 1)',
            }],
        },
        options: {
        indexAxis: 'y',  // Makes the chart horizontal
        scales: {
            x: {
                beginAtZero: true,
                title: {
                    display: true,
                    text: 'Total Score'
                }
            },
            y: {
                title: {
                    display: true,
                    text: 'Users'
                }
            }
        }
    }
    })
</script>
{% endblock %}

app/templates/user/quiz_results.html
{% extends "layout.html" %}
{% block title %}Quiz Results{% endblock %}
{% block content %}
<h1 class="page-title">Quiz Results</h1>


<div class="card">
    <div class="card-body">
        <div class="detail-item">
            <span class="detail-key">Quiz Name:</span>
            <span class="detail-value">{{ quiz.name }}</span>
        </div>

        <div class="detail-item">
            <span class="detail-key">Your Score:</span>
            <span class="detail-value">{{ score.total_scored }} / {{ quiz.questions|length }}</span>
        </div>
    </div>
</div>

{% endblock %}

app/templates/user/select-quiz.html
{% extends "layout.html" %}
{% block title %}Select Quiz{% endblock %}
{% block content %}
<h1 class="page-title">Select Quiz</h1>

<div class="card">
    <div class="card-body">
        <form method="post">
            <div class="form-group">
                <label for="subject_id" class="form-label">Select Subject</label>
                <select id="subject_id" name="subject_id" class="form-control">
                    <option value="">--Select Subject--</option>
                    {% for subject in subjects %}
                    <option value="{{ subject.id }}">{{ subject.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="chapter_id" class="form-label">Select Chapter</label>
                <select id="chapter_id" name="chapter_id" class="form-control">
                    <option value="">--Select Chapter--</option>
                    {% for chapter in chapters %}
                    <option value="{{ chapter.id }}" data-subject-id="{{ chapter.subject_id }}">{{ chapter.name }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter Quizzes</button>
        </form>
    </div>
</div>


<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date of Quiz</th>
                <th>Time Duration (In Minutes)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quizzes %}
            <tr>
                <td>{{ quiz.id }}</td>
                <td>{{ quiz.name }}</td>
                <td>{{ quiz.date_of_quiz.strftime("%Y-%m-%d") }}</td>
                <td>{{ quiz.time_duration / 60 }}</td>

                <td class="action-buttons">
                    <a href="{{ url_for('users.attempt_quiz', quiz_id=quiz.id) }}"
                        class="btn btn-edit btn-sm">Attempt</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    document.getElementById('subject_id').addEventListener('change', function () {
        subjectId = this.value;
        chapters = document.querySelectorAll('#chapter_id option')

        chapters.forEach(option => {
            if (option.dataset.subjectId == subjectId || option.value == "") {
                option.style.display = "block";
            } else {
                option.style.display = "none";
            }
        });
    })
</script>
{% endblock %}

app/templates/user/update-profile.html
{% extends "layout.html" %}
{% block title %}Update Profile{% endblock %}
{% block content %}
<h1 class="page-title">Update Profile</h1>

<form method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label(class_="form-label") }}
        {{ form.username(size=32, class_="form-control") }}
        {% if form.username.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.fullname.label(class_="form-label") }}
        {{ form.fullname(class_="form-control") }}
        {% if form.fullname.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.fullname.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.qualification.label(class_="form-label") }}
        {{ form.qualification(class_="form-control") }}
        {% if form.qualification.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.qualification.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.dob.label(class_="form-label") }}
        {{ form.dob(class_="form-control") }}
        {% if form.dob.errors %}
        <ul class="errors text-danger mt-2">
            {% for error in form.dob.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.submit(class_="btn btn-primary") }}
    </div>
</form>
{% endblock %}